AWSTemplateFormatVersion: '2010-09-09'
Description: A VPC stack to run Fargate Tasks in.

"Parameters" :
  "Bucket" :
    "Type" : "String"
    "Description" : "The bucket to write ."
  "CidrVpc" :
    "Type" : "String"
    "Default" : "10.0.0.0/16"
    "Description" : "The VPC CIDR block."
  "CidrSubnet1" :
    "Type" : "String"
    "Default" : "10.0.0.0/24"
    "Description" : "The Subnet 1 CIDR block."
  "CidrSubnet2" :
    "Type" : "String"
    "Default" : "10.0.1.0/24"
    "Description" : "The Subnet 2 CIDR block."
  "ImageName" :
    "Type" : "String"
    "Default" : "timer"
    "Description" : "The name of the task and ECR image."

Resources:

  # VPC Resources
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !Ref CidrVpc

  PublicSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
         Fn::Select:
         - 0
         - Fn::GetAZs: {Ref: 'AWS::Region'}
      VpcId: !Ref 'VPC'
      CidrBlock: !Ref CidrSubnet1
      MapPublicIpOnLaunch: true

  PublicSubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
         Fn::Select:
         - 1
         - Fn::GetAZs: {Ref: 'AWS::Region'}
      VpcId: !Ref 'VPC'
      CidrBlock: !Ref CidrSubnet2
      MapPublicIpOnLaunch: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway
  
  GatewayAttachement:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref 'VPC'
      InternetGatewayId: !Ref 'InternetGateway'
  
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref 'VPC'
  
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayAttachement
    Properties:
      RouteTableId: !Ref 'PublicRouteTable'
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref 'InternetGateway'

  RouteTableSubnet1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref 'PublicSubnetOne'
      RouteTableId: !Ref 'PublicRouteTable'

  RouteTableSubnet2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref 'PublicSubnetTwo'
      RouteTableId: !Ref 'PublicRouteTable'

  # ECS Resources
  ECSCluster:
    Type: AWS::ECS::Cluster

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to the Fargate containers
      VpcId: !Ref 'VPC'

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: 'sts:AssumeRole'
      Policies:
      - PolicyName: Task
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: 's3:PutObject'
            Resource: !Sub
              - 'arn:aws:s3:::${B}/*'
              - B: !Ref Bucket

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
      Policies:
        - PolicyName: ExecTask
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action: 
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
              Resource: !Sub
                - 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ecs/{$I}:*'
                - I: !Ref ImageName
            - Effect: Allow
              Action: 'ecr:GetAuthorizationToken'
              Resource: !GetAtt 'ECSCluster.Arn'
          
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref ImageName
      TaskRoleArn: !Ref TaskRole
      ExecutionRoleArn: !Ref TaskExecutionRole
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform: 
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX        
      Cpu: 256
      Memory: 512
      ContainerDefinitions:
        - Name: !Ref ImageName
          Image: !Sub
            - '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${I}:latest'
            - I: !Ref ImageName
          Cpu: 0
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: tcp
          Essential: true
          EntryPoint: 
            - python3.13
          LogConfiguration: 
            LogDriver: awslogs
            Options: 
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Sub
                - '/ecs/${I}'
                - I: !Ref ImageName
              mode: non-blocking
              awslogs-create-group: true
              max-buffer-size: 25m
              awslogs-stream-prefix: ecs

Outputs:
  ClusterName:
    Description: The name of the ECS cluster
    Value: !Ref 'ECSCluster'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'ClusterName' ] ]
  TaskRole:
    Description: The ARN of the Task role
    Value: !GetAtt 'TaskRole.Arn'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'TaskRole' ] ]
  TaskExecutionRole:
    Description: The ARN of the Task Execution role
    Value: !GetAtt 'TaskExecutionRole.Arn'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'TaskExecutionRole' ] ]
  VPCId:
    Description: The ID of the VPC that this stack is deployed in
    Value: !Ref 'VPC'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'VPCId' ] ]
  PublicSubnetOne:
    Description: Public subnet one
    Value: !Ref 'PublicSubnetOne'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'PublicSubnetOne' ] ]
  PublicSubnetTwo:
    Description: Public subnet two
    Value: !Ref 'PublicSubnetTwo'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'PublicSubnetTwo' ] ]
  SecurityGroup:
    Description: A security group used to allow Fargate containers to receive traffic
    Value: !Ref 'SecurityGroup'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'SecurityGroup' ] ]
  RunCmd:
    Description: AWS CLI command to run the task
    Value: !Join
      - ''
      - - 'aws ecs run-task --cluster '
        - !Ref 'ECSCluster'
        - ' --task-definition timer --launch-type "FARGATE" --network-configuration "awsvpcConfiguration={subnets=['
        - !Ref 'PublicSubnetOne'
        - ','
        - !Ref 'PublicSubnetTwo'
        - '],securityGroups=['
        - !Ref 'SecurityGroup'
        - '],assignPublicIp=ENABLED}" --overrides '
        - "'"
        - '{ "containerOverrides": [{"name": "'
        - !Ref ImageName
        - '", "command": ["app.py", "--job_id", "2", "--duration", "2", "--bucket", "'
        - !Ref Bucket
        - '"]}]}'
        - "'"
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'RunCmd' ] ]

